services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    ports:
      - "1557:1557"
    environment:
      MYSQL_ROOT_PASSWORD: tpuNjOhPrYM5
    volumes:
      - ./mysql-data:/var/lib/mysql

  redis:
    image: redis:7.4
    container_name: redis-server
    restart: always
    ports:
      - "1379:1379"
    command: >
      redis-server
      --bind 0.0.0.0
      --requirepass sB83gEM0xcN0
      --protected-mode no
    volumes:
    - ./redis-data:/data